#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if eq (include "eric-am-common-wfs.service-mesh-enabled" . ) "true" }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "eric-am-common-wfs.name" . }}-virtual-service
  labels: {{- include "eric-am-common-wfs.labels.extended-defaults" . | nindent 4 }}
  annotations: {{- include "eric-am-common-wfs.annotations" . | nindent 4 }}
spec:
  hosts:
    - {{ template "eric-am-common-wfs.name" . }}
  http:
    - match:
        - method:
            exact: GET
          uri:
            prefix: /
      retries:
        attempts: {{ .Values.highAvailability.serviceMesh.routes.get.retries.maxAttempts }}
        perTryTimeout: {{ .Values.highAvailability.serviceMesh.routes.get.retries.perTryTimeout }}
        retryOn: 5xx,reset,gateway-error,connect-failure
      timeout: {{ .Values.highAvailability.serviceMesh.routes.get.timeout }}
      route:
        - destination:
            host: {{ template "eric-am-common-wfs.name" . }}
            subset: {{ template "eric-am-common-wfs.name" . }}-v1
    - match:
        - method:
            exact: POST
          uri:
            prefix: /api/lcm/v3/resources/
      retries:
        attempts: {{ .Values.highAvailability.serviceMesh.routes.postLcm.retries.maxAttempts }}
        perTryTimeout: {{ .Values.highAvailability.serviceMesh.routes.postLcm.retries.perTryTimeout }}
        retryOn: 5xx,reset,gateway-error,connect-failure,retriable-headers
      timeout: {{ .Values.highAvailability.serviceMesh.routes.postLcm.timeout }}
      route:
        - destination:
            host: {{ template "eric-am-common-wfs.name" . }}
            subset: {{ template "eric-am-common-wfs.name" . }}-v1
    - match:
        - method:
            exact: POST
          uri:
            prefix: /api/internal/v2/namespaces/
      retries:
        attempts: {{ .Values.highAvailability.serviceMesh.routes.postInternal.retries.maxAttempts }}
        perTryTimeout: {{ .Values.highAvailability.serviceMesh.routes.postInternal.retries.perTryTimeout }}
        retryOn: 5xx,reset,gateway-error,connect-failure,retriable-headers
      timeout: {{ .Values.highAvailability.serviceMesh.routes.postInternal.timeout }}
      route:
        - destination:
            host: {{ template "eric-am-common-wfs.name" . }}
            subset: {{ template "eric-am-common-wfs.name" . }}-v1
    - match:
        - method:
            exact: POST
          uri:
            exact: /api/internal/kubernetes/pods/scale/down
      retries:
        attempts: {{ .Values.highAvailability.serviceMesh.routes.postInternal.retries.maxAttempts }}
        perTryTimeout: {{ .Values.highAvailability.serviceMesh.routes.postInternal.retries.perTryTimeout }}
        retryOn: 5xx,reset,gateway-error,connect-failure,retriable-headers
      timeout: {{ .Values.highAvailability.serviceMesh.routes.postInternal.timeout }}
      route:
        - destination:
            host: {{ template "eric-am-common-wfs.name" . }}
            subset: {{ template "eric-am-common-wfs.name" . }}-v1
    - match:
        - method:
            exact: POST
          uri:
            prefix: /api/internal/kubernetes/pvcs/
      retries:
        attempts: {{ .Values.highAvailability.serviceMesh.routes.postInternal.retries.maxAttempts }}
        perTryTimeout: {{ .Values.highAvailability.serviceMesh.routes.postInternal.retries.perTryTimeout }}
        retryOn: 5xx,reset,gateway-error,connect-failure,retriable-headers
      timeout: {{ .Values.highAvailability.serviceMesh.routes.postInternal.timeout }}
      route:
        - destination:
            host: {{ template "eric-am-common-wfs.name" . }}
            subset: {{ template "eric-am-common-wfs.name" . }}-v1
    - route:
        - destination:
            host: {{ template "eric-am-common-wfs.name" . }}
            subset: {{ template "eric-am-common-wfs.name" . }}-v1
{{- end }}