#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

ARG BASE_IMAGE \
    BASE_IMAGE_VERSION

FROM ${BASE_IMAGE}:${BASE_IMAGE_VERSION}

ARG uid=113992
ARG gid=113992

USER root

RUN curl -SsL https://arm.seli.gic.ericsson.se/artifactory/proj-em-evnfm-ci-internal-odr-generic-local/flyway/flyway-commandline-9.22.1-linux-x64.tar.gz -o /flyway-commandline.tar.gz \
    && tar -xzf /flyway-commandline.tar.gz \
    && rm /flyway-commandline.tar.gz \
    && mv /flyway-9.22.1 /flyway

COPY eric-am-common-wfs-migration/target/wfs-migration-jar-with-dependencies.jar /flyway/lib/wfs-migration.jar
COPY migrate-db.sh /migrate-db.sh

RUN chmod 755 /migrate-db.sh \
    && chmod 755 /flyway/*

USER ${uid}:${gid}

ENTRYPOINT ["/bin/sh", "-c", "/tmp/create_db.sh && /migrate-db.sh"]