#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

# Helm executor job will be rendered as k8s job only for DR check purposes
# It is not a part of eric-am-common-wfs chart

{{ if .Values.helmExecutor.job.template }}
{{ include "eric-am-common-wfs.helm-executor-job" . }}
{{- end }}